### PR TITLE
Keep formatting in user messages

### PR DESCRIPTION
**Pull request by OldStarchy**
ChatGPT can use HTML formatting but we just get plain newline characters and spaces.

Styling the messages with `pre` tells the browser to display all the whitespace as-is which keeps the messages formatted as they are intended.

### CODE REVIEW

**Comment by jcubic** [comment]
I don't see chatGPT using pre. So it will look different than on the website, am I right?

**Comment by OldStarchy** [comment]
image
image

**Comment by jcubic** [comment]
Ok, but then it should be applied when `whitespace-pre-wrap` is added not every conversation have that class.

**Comment by jcubic** [comment]
I need to close this since there are no such class. But I would prefer to have this instead:

```css
.whitespace-pre-wrap {
    white-space: pre-wrap;
}
```

**Comment by OldStarchy** [comment]
Makes sense to me. Thanks for the update.

**Pull request closed without merging**
